spring.application.name=my-portfolio-backend
spring.datasource.url=jdbc:postgresql://ep-hidden-king-zaqcxbw1-pooler.c-2.eu-west-2.aws.neon.tech/portfolio?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4a9XIuvWfNGE

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=20000

spring.sql.init.mode=always
